title: Minicraft+
description: Minicraft+, the 2D sandbox survival game.
url: https://MinicraftPlus.github.io/
repository: "MinicraftPlus/MinicraftPlus.github.io"
theme: jekyll-theme-cayman

encoding: "utf-8"